### ISSUE TITLE
Self-Hosting option for NixOS

### ISSUE THREAD

**Issue by jzbor** [ocfox/nixpkgs-tracker#10]
It would be great if there would be a `SELFHOSTING.md` manual or even better a NixOS module provided along with the package. This would make it easier to create personal instances for people who are not really familiar with deploying TypeScript projects under NixOS.

**Comment by ocfox** [comment]
Make flake supply a nixos module build to dist and nginx or caddy host it?

**Comment by jzbor** [comment]
That would be great. I think a `package` with the static files that can be served would suffice though.

**Comment by jzbor** [comment]
Thanks alot!
